import type { MergedItinerary } from '@/lib/schemas/agent';

/**
 * Export itinerary as formatted text for sharing
 */
export function exportItineraryAsText(itinerary: MergedItinerary, tripName: string): string {
  const lines: string[] = [];

  lines.push(`========================================`);
  lines.push(`${tripName.toUpperCase()}`);
  lines.push(`========================================\n`);

  if (itinerary.summary) {
    lines.push(`SUMMARY:\n${itinerary.summary}\n`);
  }

  itinerary.days.forEach((day, index) => {
    lines.push(`\n${'='.repeat(50)}`);
    lines.push(`DAY ${day.dayNumber} - ${day.date}`);
    lines.push(`${day.title}`);
    lines.push(`${'='.repeat(50)}\n`);

    if (day.transport) {
      lines.push(`🚗 TRANSPORT:`);
      if (typeof day.transport === 'string') {
        lines.push(`   ${day.transport}\n`);
      } else {
        lines.push(`   ${JSON.stringify(day.transport, null, 2)}\n`);
      }
    }

    if (day.accommodation) {
      lines.push(`🏨 ACCOMMODATION:`);
      lines.push(`   ${day.accommodation.name}`);
      if (day.accommodation.area) {
        lines.push(`   Location: ${day.accommodation.area}`);
      }
      if (day.accommodation.estimatedCost) {
        lines.push(`   Cost: ${day.accommodation.estimatedCost}`);
      }
      lines.push('');
    }

    if (day.meals && day.meals.length > 0) {
      lines.push(`🍽️ MEALS:`);
      day.meals.forEach(meal => {
        lines.push(`   ${meal.type.toUpperCase()}: ${meal.suggestion}`);
        if (meal.estimatedCost) {
          lines.push(`   Cost: ${meal.estimatedCost}`);
        }
      });
      lines.push('');
    }

    if (day.activities && day.activities.length > 0) {
      lines.push(`🎯 ACTIVITIES:`);
      day.activities.forEach((activity, idx) => {
        lines.push(`   ${idx + 1}. ${activity.name}`);
        if (activity.time) {
          lines.push(`      Time: ${activity.time}`);
        }
        if (activity.duration) {
          lines.push(`      Duration: ${activity.duration}`);
        }
        if (activity.estimatedCost) {
          lines.push(`      Cost: ${activity.estimatedCost}`);
        }
        if (activity.description) {
          lines.push(`      Details: ${activity.description}`);
        }
      });
      lines.push('');
    }
  });

  lines.push(`\n${'='.repeat(50)}`);
  lines.push(`END OF ITINERARY`);
  lines.push(`Generated by TravelPlannerAI`);
  lines.push(`${'='.repeat(50)}`);

  return lines.join('\n');
}

/**
 * Create a downloadable file for the itinerary
 */
export function downloadItineraryAsFile(itinerary: MergedItinerary, tripName: string, format: 'txt' | 'md' = 'txt') {
  const content = format === 'txt'
    ? exportItineraryAsText(itinerary, tripName)
    : exportItineraryAsMarkdown(itinerary, tripName);

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${tripName.replace(/\s+/g, '-')}-itinerary.${format}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export itinerary as markdown format
 */
function exportItineraryAsMarkdown(itinerary: MergedItinerary, tripName: string): string {
  const lines: string[] = [];

  lines.push(`# ${tripName}\n`);

  if (itinerary.summary) {
    lines.push(`## Summary\n${itinerary.summary}\n`);
  }

  itinerary.days.forEach((day) => {
    lines.push(`\n## Day ${day.dayNumber} - ${day.date}`);
    lines.push(`### ${day.title}\n`);

    if (day.transport) {
      lines.push(`#### 🚗 Transport`);
      lines.push(typeof day.transport === 'string' ? day.transport : JSON.stringify(day.transport, null, 2));
      lines.push('');
    }

    if (day.accommodation) {
      lines.push(`#### 🏨 Accommodation`);
      lines.push(`**${day.accommodation.name}**`);
      if (day.accommodation.area) {
        lines.push(`- Location: ${day.accommodation.area}`);
      }
      if (day.accommodation.estimatedCost) {
        lines.push(`- Cost: ${day.accommodation.estimatedCost}`);
      }
      lines.push('');
    }

    if (day.meals && day.meals.length > 0) {
      lines.push(`#### 🍽️ Meals\n`);
      day.meals.forEach(meal => {
        lines.push(`**${meal.type.toUpperCase()}:** ${meal.suggestion}`);
        if (meal.estimatedCost) {
          lines.push(`- Cost: ${meal.estimatedCost}`);
        }
        lines.push('');
      });
    }

    if (day.activities && day.activities.length > 0) {
      lines.push(`#### 🎯 Activities\n`);
      day.activities.forEach((activity, idx) => {
        lines.push(`${idx + 1}. **${activity.name}**`);
        if (activity.time) {
          lines.push(`   - Time: ${activity.time}`);
        }
        if (activity.duration) {
          lines.push(`   - Duration: ${activity.duration}`);
        }
        if (activity.estimatedCost) {
          lines.push(`   - Cost: ${activity.estimatedCost}`);
        }
        if (activity.description) {
          lines.push(`   - ${activity.description}`);
        }
        lines.push('');
      });
    }
  });

  lines.push(`---\n*Generated by TravelPlannerAI*`);

  return lines.join('\n');
}

/**
 * Copy itinerary to clipboard
 */
export async function copyItineraryToClipboard(itinerary: MergedItinerary, tripName: string): Promise<boolean> {
  try {
    const text = exportItineraryAsText(itinerary, tripName);
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}
